# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'AppWithoutStoryBoard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#   pod 'MaterialComponents'
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  #Pods for AppWithoutStoryBoard

end
